# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export PATH="$PATH:`yarn global bin`"

# Do not update homebrew when running brew install due to slow internet speeds
# https://github.com/Homebrew/brew/issues/1670#issuecomment-267096602
export HOMEBREW_NO_AUTO_UPDATE=1

#Clojure(script) aliases
alias lrs="lein ring server"
alias lbuildo="lein cljsbuild once"
alias lbuildc="lein cljsbuild clean"
alias lbuilda="lein cljsbuild auto"

alias be="bundle exec"

# Project aliases
alias blog="cd ~/GoogleDrive/programming/Projects/pszals.github.io"
alias comment="cd ~/GoogleDrive/programming/Projects/comment_creator/teacher_comments"
alias sandbox="cd ~/GoogleDrive/programming/Projects/sandbox"
alias katas="cd ~/GoogleDrive/programming/Projects/ruby_katas"
alias calculator="cd ~/GoogleDrive/programming/Projects/calculator"

# Dotfile aliases
alias zshrc="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export PATH="/usr/local/bin:/Users/pszalwinski/.rvm/gems/ruby-2.0.0-p247/bin:/Users/pszalwinski/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/pszalwinski/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/pszalwinski/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/MacGPG2/bin:/usr/local/bin/scripts:$HOME/.rvm/bin"
# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
